default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: curso_rails
  username: root
  password: 1234
  host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
